#!/bin/bash

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
# Export GPG tty
export GPG_TTY=$(tty)
#export DOTFILES="$HOME/Github/dotfiles"
export DOTFILES_CONFIGURATIONS="$DOTFILES/df.configs"
export CRED_CONF="$DOTFILES_CONFIGURATIONS/cred.config.json"
#export NUCLEUS="$HOME/Nucleus"
#export NUCLEUS_BIN="$NUCLEUS/bin"

export GOPATH=~/go
export GOBIN=$GOPATH/bin
#export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/google-cloud-sdk/bin"
export PATH="$PATH:$HOME/.cargo/bin"

if [ -f $DOTFILES/.quiet ]; then 
    export QUIET=true
else
    export QUIET=false
fi

if [ "$QUIET" = "true" ]; then
    tput setaf 9; echo "[INFO] ... quiet=$QUIET"
fi

function source_libraries () {
    for f in $DOTFILES/src/*
    do
        if [ -f "$f" ]; then
            source $f # . $f
            if [ "$QUIET" != "true" ]; then
                tput setaf 9; echo "[INFO] ... loaded $(basename $f)"
            fi
        fi
    done
}

source_libraries

tput setaf 9; echo "[INFO] ... Loading done. exit code: $?"


if [ "$EUID" -eq 0 ]; then
    echo "WTFFFF ????"
fi


# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/Users/ial-ah/google-cloud-sdk/Desktop/path.bash.inc' ]; then source '/Users/ial-ah/Desktop/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '/Users/ial-ah/google-cloud-sdk/Desktop/completion.bash.inc' ]; then source '/Users/ial-ah/Desktop/google-cloud-sdk/completion.bash.inc'; fi
