#!/bin/bash

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
export PATH="/usr/local/sbin:$PATH"

function source_libraries () {
    for f in $DOTFILES/src/*
    do
        if [ -f "$f" ]; then
            source $f # . $f
            tput setaf 9; echo "[INFO] ... Loading $(basename $f).sh"
        fi
    done
}

source_libraries

echo "\n[INFO] ... Loading done. (Exit status: $?)"