#!/bin/zsh

export DOTFILES=$DOTFILES_PATH


if [ -f $DOTFILES_PATH/.quiet ]; then 
    export QUIET=true
else
    export QUIET=false
fi

if [ "$QUIET" = "true" ]; then
    tput setaf 9; echo "[INFO] ... quiet=$QUIET"
fi

function source_libraries () {
    for f in $DOTFILES_PATH/src/*
    do
        if [ -f "$f" ]; then
            source $f # . $f
            if [ "$QUIET" != "true" ]; then
                tput setaf 9; echo "[INFO] ... loaded $(basename $f)"
            fi
        fi
    done
}

source_libraries

tput setaf 9; echo "[INFO] ... Loading done. exit code: $?"