#!/bin/bash

if ! [ -x "$(command -v mysql)" ]; then
    alias mysql='/usr/local/mysql/bin/mysql'
fi

_default_mysql=".known_databases.mysql"

#decap

# Default mysql connection
function mysql () {
    opt="$1"
    if [ "$opt" = "o" ]; then
        mysql_du=$(extract_from_json $CRED_CONF "$_default_mysql.user")
        mysql_dh=$(extract_from_json $CRED_CONF "$_default_mysql.host")
        mysql_dp=$(extract_from_json $CRED_CONF "$_default_mysql.port")
        mysql_dpw=$(extract_from_json $CRED_CONF "$_default_mysql.password")
        mysql -h $mysql_dh -u $mysql_du "-p$mysql_dpw"
    else
        mysql $@
    fi
}

$@
