#!/bin/bash

# DOTFILES | DOTFILESMACHINES | DOTFILESKEYS

#source $DOTFILES/.src/json

_km=".known_machines"

function local_ssh () {
    user="$1"
    adress="$2"
    sentence="$user@$adress"
    sudo ssh "$sentence"
}

function aws_ssh () {
    # Europ central connection
    user="$1"
    adress="$user@$2.eu-central-1.compute.amazonaws.com"
    pem_key_regex_dir="$3"
    ssh -i "$pem_key_regex_dir" "$adress"
}

function sshit () {
    opt="$1"
    if [ "$opt" = "--local" ]; then
        local_ssh "${@:2}"
    elif [ "$opt" = "--aws" ]; then
        aws_ssh "${@:2}"
    elif [ "$opt" = "--known" ]; then
        machine="$2"
        _type=$(extract_from_json $CRED_CONF "$_km.$machine.type")
        user=$(extract_from_json $CRED_CONF "$_km.$machine.user")
        adress=$(extract_from_json $CRED_CONF "$_km.$machine.adress")
        pem_key=$(extract_from_json $CRED_CONF "$_km.$machine.pem_key")
        if [ "$_type" = "aws" ]; then
            aws_ssh "$user" "$adress" "$HOME/$pem_key"
        elif [ "$_type" = "local" ]; then
            local_ssh $user $adress
        fi
    else
        sudo ssh $@
    fi
}

$@
