#!/usr/bin/env bash

# Print public SSH key to clipboard. Generate it if necessary


function ssh-keygen () {
    file="$HOME/.ssh/id_rsa.pub"
    if [ ! -f "$file" ]; then
      ssh-keygen -t rsa
    else
      ssh-keygen $@
    fi
}

$@
