#!/bin/bash

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
    # Vim fast cmd line

	if [ $# -eq 0 ]; then
		vim .;
	else
		vim "$@";
	fi;
}


# Atom
function atom () {
    # atom fast cmd line

    if [ $# -eq 0 ]; then
        atom .
    else
        atom "$@"
    fi;
}

$@
