#!/bin/bash


function extract_from_json () {
    f="$1"
    cat $f | jq -r "${@:2}"
}

alias efj='extract_from_json'


# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
	if [ -t 0 ]; then # argument
		python -mjson.tool <<< "$*" | pygmentize -l javascript;
	else # pipe
		python -mjson.tool | pygmentize -l javascript;
	fi;
}

$@
