#!/bin/bash


source $DOTFILES/.lib/json

alias mysql='/usr/local/mysql/bin/mysql'

mysql_du=$(extract_from_json $DF_DATABASES .mysql.user)
mysql_dh=$(extract_from_json $DF_DATABASES .mysql.host)
mysql_dp=$(extract_from_json $DF_DATABASES .mysql.port)
mysql_dpw=$(extract_from_json $DF_DATABASES .mysql.password)

# Default mysql connection
function gomysql () {
    echo "$mysql_dh $mysql_du $mysql_dpw"
    mysql -h $mysql_dh -u $mysql_du "-p$mysql_dpw"
}

$@
