#!/bin/zsh

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"
# Export GPG tty
export GPG_TTY=$(tty)
export CRED_CONF="$DOTFILES/etc/cred.config.json"

export GOPATH=~/go
export GO111MODULE=on
export GOBIN=$GOPATH/bin
export PATH="/usr/local/go/bin:$PATH"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/google-cloud-sdk/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export AWS_PROFILE="nexus"