#!/bin/bash

alias old_bash='/bin/bash'
alias bash='/usr/local/bin/bash'

function __chsh () {
    version="$1"
    path="$1"
    if [ "$version" =~ "4*" ] || [ "$version" = "new" ] ; then
        if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
            echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
            chsh -s /usr/local/bin/bash;
        fi;
    elif [ "$version" =~ "3*" ] || [ "$version" = "old" ]; then
        if ! fgrep -q '/bin/bash' /etc/shells; then
            echo '/bin/bash' | sudo tee -a /etc/shells;
            chsh -s /usr/local/bin/bash;
        fi;
    fi
}
