#!/bin/bash

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
    # Vim fast cmd line

	if [ $# -eq 0 ]; then
		vim .;
	else
		vim "$@";
	fi;
}


# Atom
function goatom () {
    # atom fast cmd line
    if [ $# -eq 0 ]; then
        atom .
    else
        atom "$@"
    fi;
}

#vscode

alias vs='code'
alias vscode='code'

function vsc () {
    if [ "$1" = "" ]; then
        code .
    fi
    code $@
}

$@
