#!/bin/bash

function hashmd5 () {
    opt="$1"
    if [ "$opt" = "--md5" ]; then
        md5 -s $2
    else
        echo "Not implemented"
    fi
}

function b64 () {
    echo $1 | base64
}

function 64b () {
    echo $1 | base64 --decode
}
