#!/bin/bash

function find () {
    opt="$1"
    f="$2"
    if [ "$opt" = "--home" ] || [ "$opt" = "home" ]; then
        find "$HOME" -name "$f"
    elif [ "$opt" = "--here" ] || [ "$opt" = "here" ]; then
        find "$PWD" -name "$f"
    elif [ "$opt" = "--github" ] || [ "$opt" = "github" ]; then
        find "$HOME/Github" -name $f
    elif [ "$opt" = "--all" ] || [ "$opt" = "all" ]; then
        find / -name "$f"
    else
        find "$opt" -name "$f"
    fi
}

$@
