#!/bin/bash


function gitconf () {
    user=$1
    if [ "$user" = "" ]; then
        user=default
    fi
    username=$(extract_from_json $CRED_CONF .git.$user.username)
    email=$(extract_from_json $CRED_CONF .git.$user.email)

    if [ ! "$username" = "" ]; then
        git config --global user.name "$username"
        echo "configured user name: $username"
    fi
    if [ ! "$email" = "" ]; then
        git config --global user.email "$email"
        echo "configured user email: $email"
    fi
}