#!/bin/bash

export GOGOBASE=$HOME/source

function gogo() {
	if [ "$1" = "gh" ]; then 
		cd $GOGOBASE/github.com
	elif [ "$1" = "df" ] || [ "$1" = "dotfiles" ] ; then
		cd $GOGOBASE/github.com/a-hilaly/dotfiles
	elif [ "$1" = "aws" ] ; then
		cd $GOGOBASE/github.com/aws
	elif [ "$1" = "awslabs" ] ; then
		cd $GOGOBASE/github.com/awslabs
	elif [ "$1" = "kro" ] ; then
		cd $GOGOBASE/github.com/kubernetes-sigs/kro	
	elif [ "$1" = "ack" ]; then
		cd $GOGOBASE/github.com/aws-controllers-k8s
	elif [ "$1" = "me" ]; then
		cd $GOGOBASE/github.com/a-hilaly
	elif [ "$1" = "wip" ]; then
		cd $GOGOBASE/wip
	elif [ "$1" = "random" ]; then
		cd $GOGOBASE/random
	elif [ "$1" = "ks" ] || [ "$1" = "k-sigs" ] || [ "$1" = "sigs" ]; then
		cd $GOGOBASE/github.com/kubernetes-sigs
	elif [ "$1" = "kube" ] || [ "$1" = "k8s" ] || [ "$1" = "k" ]; then
		cd $GOGOBASE/github.com/kubernetes
	elif [ "$1" = "k/k" ]; then
		cd $GOGOBASE/github.com/kubernetes/kubernetes
	elif [ "$1" = "csi" ]; then
		cd $GOGOBASE/github.com/kubernetes-csi
	else
		if [ -d "$GOGOBASE/wip/$1" ]; then
			cd "$GOGOBASE/wip/$1"
		elif [ -d "$GOGOBASE/github.com/$1" ]; then
			cd "$GOGOBASE/github.com/$1"
		elif [ -d "$GOGOBASE/github.com/a-hilaly/$1" ]; then
			cd "$GOGOBASE/github.com/a-hilaly/$1"
		elif [ -d "$GOGOBASE/random/$1" ]; then
			cd "$GOGOBASE/random/$1"
		else
			echo "gogo: '$1' not found"
		fi
	fi
}

