#!/bin/bash

export GOGOBASE=~/source

function gogo() {
	if [ "$1" = "gh" ]; then 
		cd $GOGOBASE/github.com
	elif [ "$1" = "me" ]; then
		cd $GOGOBASE/github.com/a-hilaly
	elif [ "$1" = "dh" ]; then
		cd $GOGOBASE/github.com/destructhub
	elif [ "$1" = "kube" ]; then
		cd $GOGOBASE/github.com
	elif [ "$1" = "sii" ]; then
		cd $GOGOBASE/github.com/siisxb
	elif [ "$1" = "supbank" ];then
		cd $GOGOBASE/gitlab.com/supbank
	elif [ "$1" = "kubei" ]; then
		cd $GOGOBASE/github.com/kubernetes-incubator
	else
		cd $GOGOBASE/github.com/$1
	fi
}

