#!/bin/bash

alias venv='virtualenv'

# Create virtual env and source it
function goenv () {
    if [ -f $1/bin/activate ]; then
        source $1/bin/activate
    else
        venv $1
        source $1/bin/activate
    fi
}

# Deactivate virtual env
function quit () {
    deactivate
}

$@
